"""Build only explicitly selected public-facing content; never copy private evidence."""
from pathlib import Path
import csv, html, json
ROOT=Path(__file__).resolve().parent
SITE=ROOT/'site'
e=html.escape
NAV='<a class="skip" href="#main">Skip to content</a><header><a class="brand" href="index.html">Russell Bishop<span aria-hidden="true"> / </span>AI & Cloud</a><nav aria-label="Main navigation"><a href="projects.html">Projects</a><a href="architecture.html">Architecture</a><a href="demo.html">Try the demo</a></nav></header>'
FOOT='<footer>Russell Bishop · AI engineering & cloud architecture portfolio · Project evidence reviewed 19 September 2026 · AWS website verified live 20 September 2026.<br>Project status and limitations are stated individually. Synthetic demo data; no trading or investment recommendations.</footer>'
def page(filename,title,content,script=None):
    (SITE/filename).write_text('<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Russell Bishop: AI application development, AWS architecture, data quality and governed automation. Explore reproducible demonstrations and engineering case studies."><title>'+e(title)+' | Russell Bishop</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css"></head><body>'+NAV+'<main id="main">'+content+'</main>'+FOOT+('<script src="assets/'+script+'" defer></script>' if script else '')+'</body></html>\n')
model_path=ROOT/'data/projects.json'
if model_path.exists():
    rows=[dict(project_id=p['id'],project=p['name'],priority=p['priority'],status=p['status'],evidence=p['evidence'],next_action=p['next_action'],completion_gate=p['completion_gate']) for p in json.loads(model_path.read_text())['projects']]
else:
    register=ROOT.parent/'PROJECT_REGISTER.csv'
    if not register.exists(): register=ROOT/'PUBLIC_PROJECT_REGISTER.csv'
    rows=list(csv.DictReader(register.open()))
public=[r for r in rows if r['project_id'] not in {'PROJECT-413531db0fb0','JRB'}]
page('index.html','AI engineering & cloud architecture','''<section class="hero"><div class="eyebrow">Applications · Architecture · Evidence</div><h1>AI systems you can<br>inspect and explain.</h1><p class="lead">I work across AI applications, cloud architecture and data pipelines. This portfolio connects implementation decisions to reproducible examples, validation evidence and clearly stated limits.</p><div class="actions"><a class="button" href="demo.html">Run the data-quality demo</a><a class="button secondary" href="projects.html">Explore all projects</a></div></section><div class="metrics"><div><strong>37</strong><span>Projects and supporting workstreams catalogued</span></div><div><strong>30</strong><span>AIVouch backend tests passed in local validation</span></div><div><strong>7</strong><span>Data-quality unit tests in the initial validation suite</span></div></div><section><div class="eyebrow">Selected engineering work</div><h2>Four perspectives on building useful AI.</h2><div class="grid"><article class="card"><span class="badge">AWS / Python / Infrastructure as code</span><h3>Event-driven data quality</h3><p>A bounded validator for financial records, with version-aware S3 ingestion, a Lambda implementation and scoped output permissions. Builds on recovered MSc AWS lab evidence.</p><a href="aws.html">Explore the AWS case study →</a></article><article class="card"><span class="badge">FastAPI / Android / Applied AI</span><h3>AIVouch</h3><p>An AI visibility application that preserves scan evidence and turns findings into reviewed fixes and follow-up checks. Includes API, mobile and recovery validation.</p><a href="aivouch.html">Explore the application →</a></article><article class="card"><span class="badge">Financial data / Provenance / Evaluation</span><h3>Financial AI research</h3><p>Market ingestion, observation registers and source-health monitoring. A focus on point-in-time provenance makes data issues visible before model conclusions.</p><a href="finance.html">Explore the research pipeline →</a></article><article class="card"><span class="badge">Agents / Scheduling / Governance</span><h3>AI OS & automation</h3><p>Local orchestration, scheduled work and governed agent workflows. Operational status is separated from historical completion labels.</p><a href="aios.html">Explore the automation work →</a></article></div></section><section class="panel"><div class="eyebrow">How to review this portfolio</div><h2>Start with the demo. Follow the evidence.</h2><p>Run a sample, inspect the architecture, then download the implementation. The wider catalogue includes MSc coursework and PhD proposal work; a listed project is not necessarily a finished product.</p><div class="actions"><a class="button secondary" href="architecture.html">Architecture & trade-offs</a><a class="button secondary" href="downloads/portfolio-source.zip" download>Download demo source</a></div></section>''')
page('demo.html','Interactive data-quality demonstration','''<section class="hero"><div class="eyebrow">Interactive demonstration</div><h1>Catch data problems<br>before they become claims.</h1><p class="lead">Edit the sample and inspect record-level validation. The exercise checks positive finite prices, duplicate asset/date pairs and observation/acquisition ordering.</p><div class="notice">This demo runs in your browser and sends no data to AWS. The downloadable Python implementation provides the S3/Lambda path. Cloud deployment and integration-test evidence are reported separately.</div></section><section class="grid"><div class="panel"><h2>1. Choose or edit input</h2><label for="scenario">Sample</label><select id="scenario"><option value="issues">Duplicate, price and date issues</option><option value="clean">Valid sample</option></select><p><label for="payload">JSON input · up to 1,000 rows / 256 KiB</label><textarea id="payload" spellcheck="false"></textarea></p><button id="run">Run validation</button></div><div class="panel"><h2>2. Inspect the result</h2><p>Row numbers start at zero. A record with several issues counts once as an invalid row.</p><pre id="result" role="status" aria-live="polite">Ready.</pre><p>A PASS only means these checks passed. It does not establish source accuracy, investment value or historical point-in-time availability.</p></div></section><section><h2>From browser exercise to event-driven service</h2><div class="flow"><div><b>01 / INPUT</b>Private, versioned S3<small>incoming/*.json</small></div><div><b>02 / PROCESS</b>Python Lambda<small>Bounded read and validation</small></div><div><b>03 / OUTPUT</b>Separate private S3<small>Deterministic result key</small></div><div><b>04 / OBSERVE</b>CloudWatch logs<small>Seven-day retention</small></div></div><a href="architecture.html">Read the architecture decisions →</a></section>''','demo.js')
cases={
'aws.html':('AWS data-quality pipeline','AWS / Python / CloudFormation','Turn an MSc cloud lab into a reproducible engineering demonstration.', 'The recovered coursework describes a cloud migration and S3/Lambda event workflow. Historical screenshots show an S3 upload, Lambda metrics, CloudWatch and IAM setup. This iteration adds executable validation and infrastructure as code.', [('Implementation','Private, encrypted, versioned input and result buckets; an event-driven Python function; narrow input/output permissions; deterministic result keys tied to object versions.'),('Validation evidence','Seven initial Python unit tests cover valid input, duplicate records, invalid prices, acquisition ordering, input limits, versioned repeat delivery and oversized objects. Additional release checks cover browser behavior and infrastructure schemas.'),('Architecture decision','Separate input and result buckets avoid output-trigger recursion. Object version IDs bind processing to the uploaded version. HTTPS delivery through CloudFront keeps the website bucket private.'),('Limits and next steps','The portfolio website uses its own AWS hosting stack. Recovered screenshots document the earlier MSc lab. The separate S3-to-Lambda data pipeline still requires deployment and a cloud smoke test. Demo error retries are disabled; production needs a failure queue, alarms and recovery procedures.')]),
'aivouch.html':('AIVouch','Applied AI / API / Android','Make AI visibility findings inspectable and actionable.', 'AIVouch checks whether AI answer engines mention a business for relevant buyer questions. The implementation preserves scan evidence and supports reviewed fixes and subsequent tracking.', [('Implementation','FastAPI API, PostgreSQL deployment and migrations, Expo/React Native Android client and PWA. Scan evidence distinguishes demonstration results from live modes.'),('Validation evidence','Thirty backend tests passed in the local audit, including demo scan flow and account export/deletion. Two concurrent test suites passed with isolated disposable databases. Mobile type checking and the API URL build guard passed.'),('Engineering decision','Separate liveness from configuration readiness, keep a recoverable accepted baseline, and require review before applying consequential suggestions. A local bundle restore verified tracked Git history.'),('Limits and next steps','Historical beta documentation records Android → Render → Supabase → Gemini acceptance. Current service health is unverified. Live AI quality, password recovery and a production-data restore still need evidence. This portfolio site does not claim the AIVouch application is hosted on AWS.')]),
'finance.html':('Financial AI research','Data engineering / Provenance / Evaluation','Make data lineage part of the research result.', 'The finance work includes market capture, EWMA shadow observation, gold forward observation and verified metals monitoring. The current engineering priority is reproducible evidence rather than unsupported strategy-performance claims.', [('Available work','Local research and ingestion stages, dated observations and source-health artifacts are catalogued. The browser demo illustrates selected data-quality checks with synthetic records.'),('Findings from the audit','Recent captures coexist with stale or failed sources. The inspected gold ledger needs a point-in-time review; the EWMA aggregate register needs reconciliation with individual run artifacts.'),('Engineering decision','Keep observation date, acquisition date and source provenance distinct. Preserve corrections and expose missing data before making comparative evaluation or model claims.'),('Limits and next steps','Resolve capture gaps, define baselines and leakage-safe evaluation, reconcile the observation history and verify independent recovery. No profitability, live trading readiness or forecast-quality claim is made.')]),
'aios.html':('AI OS & governed automation','Agents / Operations / Recovery','Coordinate work without losing the evidence behind its status.', 'AI OS brings together a local dashboard, scheduled processing, project registers and agent workflows. The portfolio focuses on the practical boundaries between orchestration, authorization and observed operation.', [('Available work','Local dashboard and central-cycle operation were observed in the session audit. Project registers identify automation, archive, research and financial pipelines with explicit next actions.'),('Operational improvements','Sleep inhibition protects recognized active work. Hybrid backup scheduling now targets canonical source files, with checksum and sample-restore verification for a local snapshot.'),('Engineering decision','Do not equate a historical COMPLETE label with a working connector. Keep source-health checks and release evidence separate from task bookkeeping.'),('Limits and next steps','Connector authentication, archive freshness and independent backup recovery remain incomplete. The local sleep guard is not a cloud availability guarantee. Remote operation requires authentication, tested recovery and evaluated workflows.')])}
for filename,(title,tags,headline,intro,sections) in cases.items():
 content='<section class="hero"><div class="eyebrow">'+e(tags)+'</div><h1>'+e(title)+'</h1><p class="lead">'+e(headline)+'</p><p>'+e(intro)+'</p></section><div class="grid">'+''.join('<section class="panel"><h2>'+e(h)+'</h2><p>'+e(p)+'</p></section>' for h,p in sections)+'</div><div class="actions"><a class="button secondary" href="projects.html">All projects</a><a class="button" href="demo.html">Run the demonstration</a></div>'
 page(filename,title,content)
page('architecture.html','Architecture & deployment','''<section class="hero"><div class="eyebrow">Design decisions</div><h1>Small components.<br>Explicit boundaries.</h1><p class="lead">The portfolio host and the data-processing demonstration are separate stacks. That keeps a public demonstration accessible without exposing data ingestion or coupling the website to an always-on service.</p></section><section><h2>Portfolio delivery</h2><div class="flow"><div><b>VIEWER</b>Browser<small>HTTPS only after redirect</small></div><div><b>EDGE</b>CloudFront<small>Cache + security headers</small></div><div><b>ORIGIN</b>Private S3<small>Signed origin access</small></div></div><p>CloudFormation defines the origin access control, distribution and scoped bucket policy. Only the reviewed site directory is uploaded. Source archives are assembled from an explicit allowlist.</p></section><section><h2>Data-quality demonstration</h2><div class="flow"><div><b>INGEST</b>Versioned S3 object<small>Limited prefix and JSON suffix</small></div><div><b>COMPUTE</b>Python Lambda<small>15-second timeout / 128 MB</small></div><div><b>RESULT</b>Separate private bucket<small>Version-derived output name</small></div></div><div class="grid"><article class="panel"><h3>Security</h3><p>Block public S3 access, enforce HTTPS, encrypt at rest and limit object permissions. The website contains no account identifiers, credentials, private documents or original screenshots.</p></article><article class="panel"><h3>Cost boundaries</h3><p>No always-on VM, database or NAT gateway is required for the portfolio host. Free-tier eligibility and credits depend on the account. Storage, delivery, logs and requests can still incur charges; a budget alert is not a spending cap.</p></article><article class="panel"><h3>Recovery</h3><p>Site releases are hashed and archived locally. Re-upload a retained release to roll back. S3 buckets are retained on stack deletion, so explicit cleanup is needed to stop residual storage charges.</p></article><article class="panel"><h3>Current limits</h3><p>The browser exercise runs locally. The separate pipeline needs deployment and an integration check before it can be described as cloud-verified. Production ingestion also needs failure handling, alarms and operational ownership.</p></article></div></section><section><h2>Inspect and reproduce</h2><div class="actions"><a class="button" href="downloads/portfolio-source.zip" download>Download source bundle</a><a class="button secondary" href="downloads/hosting.json" download>Hosting template</a><a class="button secondary" href="downloads/data-quality.json" download>Pipeline template</a></div><p>Official references: <a href="https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html">CloudFront origin access control</a> and <a href="https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html">S3 events with Lambda</a>.</p></section>''')
def category(row):
 ident=row['project_id']
 if row['priority']=='ACADEMIC' or ident.startswith(('PHD-','MSC-','RESEARCH-')):return 'Research & MSc'
 if ident.startswith('FINANCE-') or ident in {'HYBRID','FINVIZ','BITGET','REVX'}:return 'Financial systems'
 if ident in {'AIVOUCH','AWS-PORTFOLIO','JOBS'}:return 'Applications & cloud'
 return 'Agents & automation'
cards=[]
for r in public:
 cards.append('<article class="card" data-category="'+e(category(r))+'"><span class="badge">'+e(category(r))+'</span><h3>'+e(r['project'])+'</h3><p><strong>Recorded status:</strong> '+e(r['status'].replace('_',' ').lower())+'</p><p>'+e(r['evidence'])+'</p><details><summary>Next step & completion gate</summary><p>'+e(r['next_action'])+'</p><p>'+e(r['completion_gate'])+'</p></details></article>')
controls='<div class="filters"><label>Search projects<input id="search" type="search" placeholder="AWS, MSc, agents…"></label><label>Area<select id="category"><option value="">All areas</option>'+''.join('<option>'+e(c)+'</option>' for c in sorted({category(r) for r in public}))+'</select></label></div><p id="count" role="status" aria-live="polite"></p>'
page('projects.html','Project catalogue','<section class="hero"><div class="eyebrow">The wider portfolio</div><h1>Projects & research.</h1><p class="lead">'+str(len(public))+' projects and supporting workstreams, including MSc coursework, PhD proposal work, applications and automation.</p><p>These are not '+str(len(public))+' finished products. Each entry states the recorded evidence and the work needed to meet its completion gate.</p></section>'+controls+'<div id="cards" class="grid">'+''.join(cards)+'</div>','catalogue.js')
page('404.html','Page not found','<section class="hero"><h1>Page not found.</h1><p>Return to the portfolio or explore the project catalogue.</p><a class="button" href="index.html">Back to portfolio</a></section>')
print('Built',len(list(SITE.glob('*.html'))),'HTML pages; catalogue:',len(public))
